#### general settings
name: DANx2_setting1_google_x4ds
use_tb_logger: true
model: blind
distortion: sr
scale: 2
gpu_ids: [0, 1, 2, 3, 4, 5, 6, 7]
pca_matrix_path: ../../../pca_matrix/DANv2/pca_matrix.pth

degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 4.0
  rate_iso: 1.0
  random_disturb: false

#### datasets
datasets:
  train:
    name: data3450_x4ds_x2HR
    mode: GT
    dataroot_GT: /content/drive/MyDrive/tapmobileTestProj/trainData/data_resized/x4ds_2xHR_forLMDB/HRx2.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 4
    GT_size: 128
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K_valid_x4ds
    mode: LQGT
    dataroot_GT: /content/drive/MyDrive/tapmobileTestProj/valData/DIV2K_valid_x4ds/HRx2.lmdb
    dataroot_LQ: /content/drive/MyDrive/tapmobileTestProj/valData/DIV2K_valid_x4ds/LRblurx2.lmdb

#### network structures
network_G:
  which_model_G: DAN
  setting:
    nf: 64
    nb: 10
    ng: 5
    input_para: 10
    loop: 4
    kernel_size: 21

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 16
  warmup_iter: -1  # no warm up
  lr_steps: [4, 8, 12]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 1.1e1

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 2.5e3
